
from support.path_support import merge_path
from model import context_model
from repository import repository
from support.config_support import config

TEST_LOCAL_ROOT_PATH = "./uttest/tmp/"
TEST_CLOUD_ROOT_PATH = config.get_cloud_root_path()
TEST_FOLDER_NAME = "test_folder"
TEST_SWAP_FOLDER_NAME = "swap"
TEST_DB_FILE_NAME = "." + TEST_FOLDER_NAME + ".json"

TEST_LOCAL_BASE_PATH = merge_path([TEST_LOCAL_ROOT_PATH, TEST_FOLDER_NAME])
TEST_CLOUD_BASE_PATH = merge_path([TEST_CLOUD_ROOT_PATH, TEST_FOLDER_NAME])
TEST_SWAP_BASE_PATH = merge_path([TEST_LOCAL_ROOT_PATH, TEST_SWAP_FOLDER_NAME])

TEST_LOCAL_DB_PATH = TEST_LOCAL_BASE_PATH + "/" + TEST_DB_FILE_NAME
TEST_CLOUD_DB_PATH = TEST_CLOUD_BASE_PATH + "/" + TEST_DB_FILE_NAME
TEST_SWAP_DB_PATH = TEST_SWAP_BASE_PATH + "/" + TEST_DB_FILE_NAME

SAME_FOLDER_NAME = "same_folder"
SAME_FILE_NAME = "same.md"
TO_DELETE_FILE_NAME = "to_delete.md"
TO_CREATE_FILE_NAME = "to_create.md"
TO_UPDATE_FILE_NAME = "to_update.md"

FILE_DEFAULT_CONTENT = "abc"
FILE_UPDATE_CONTENT = "abcdef"

OLD_TIEMSTAMPLE = 1600000000
NEW_TIMESTAMPLE = 1700000000

TEST_FOLDER_CONTEXT = context_model.FolderContext(TEST_LOCAL_BASE_PATH, TEST_CLOUD_BASE_PATH, TEST_SWAP_BASE_PATH)
TEST_DB_CONTEXT = context_model.DBContext(TEST_LOCAL_BASE_PATH, TEST_CLOUD_BASE_PATH, TEST_SWAP_BASE_PATH)
TEST_LOCAL_DB = repository.FileDB(TEST_FOLDER_CONTEXT, TEST_DB_CONTEXT)

TEST_MODE_MASTER = "master"
TEST_MODE_SUBORDINATE = "subordinate"
